# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setting.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow, QApplication, QComboBox, QLabel, QPushButton, QDialog, QVBoxLayout
import serial.tools.list_ports


def get_connected_com_ports():
    com_ports = []
    available_ports = list(serial.tools.list_ports.comports())
    for port, desc, hwid in available_ports:
        com_ports.append(port)
    return com_ports

class Ui_Dialog(object):
    com = 0
    BaudRate = 0
    DataBits = 0
    Parity = 0
    StopBits = 0

    def on_ok_button_clicked(self):
        
        print("ok clicked")
        self.com = self.comboBox_2.currentText()
        self.BaudRate = self.comboBox.currentText()
        self.DataBits = self.comboBox_3.currentText()
        self.Parity = self.comboBox_4.currentText()
        self.StopBits = self.comboBox_5.currentText()
       
        if(self.com != None):
            print(self.com)
            print(self.BaudRate)
            print(self.DataBits)
            print(self.Parity)
            print(self.StopBits)
            print("--------")
        
        
        
        
        
       
        
        
    
    def setupUi(self, Dialog):
        trans = QtCore.QCoreApplication.translate
        Dialog.setObjectName("Dialog")
        Dialog.resize(499, 368)
        Dialog.setSizeGripEnabled(True)
        
        

        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(140, 317, 192, 31))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        
        #self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        
        self.pushButton_0 = QPushButton(Dialog)
        self.pushButton_0.setGeometry(QtCore.QRect(140, 320, 90, 25))  # Adjust the geometry as needed
        self.pushButton_0.setObjectName("pushButton")
        self.pushButton_0.setText("Ok")

        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel)
        

        # self.pushButton_0.clicked.connect(self.closeDialog)
        

        

        
        
       
        self.buttonBox.setObjectName("buttonBox")

        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 110, 191, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label.setFont(font)
        self.label.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(100, 150, 71, 22))
        self.comboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLengthWithIcon)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(40, 150, 61, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(70, 20, 221, 21))
        self.label_3.setObjectName("label_3")
        self.comboBox_2 = QtWidgets.QComboBox(Dialog)
        self.comboBox_2.setGeometry(QtCore.QRect(70, 50, 221, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(260, 150, 61, 16))
        self.label_4.setObjectName("label_4")
        self.comboBox_3 = QtWidgets.QComboBox(Dialog)
        self.comboBox_3.setGeometry(QtCore.QRect(320, 150, 69, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(40, 190, 61, 20))
        self.label_5.setObjectName("label_5")
        self.comboBox_4 = QtWidgets.QComboBox(Dialog)
        self.comboBox_4.setGeometry(QtCore.QRect(100, 190, 69, 22))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(260, 190, 61, 20))
        self.label_6.setObjectName("label_6")
        self.comboBox_5 = QtWidgets.QComboBox(Dialog)
        self.comboBox_5.setGeometry(QtCore.QRect(320, 190, 69, 22))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        
        

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "COM Port Settings"))
        self.comboBox.setItemText(0, _translate("Dialog", "110"))
        self.comboBox.setItemText(1, _translate("Dialog", "300"))
        self.comboBox.setItemText(2, _translate("Dialog", "600"))
        self.comboBox.setItemText(3, _translate("Dialog", "1200"))
        self.comboBox.setItemText(4, _translate("Dialog", "2400"))
        self.comboBox.setItemText(5, _translate("Dialog", "4800"))
        self.comboBox.setItemText(6, _translate("Dialog", "9600"))
        self.comboBox.setItemText(7, _translate("Dialog", "14400"))
        self.comboBox.setItemText(8, _translate("Dialog", "19200"))
        self.comboBox.setItemText(9, _translate("Dialog", "28800"))
        self.comboBox.setItemText(10, _translate("Dialog", "38400"))
        self.comboBox.setItemText(11, _translate("Dialog", "56000"))
        self.comboBox.setItemText(12, _translate("Dialog", "57600"))
        self.comboBox.setItemText(13, _translate("Dialog", "115200"))
        self.comboBox.setItemText(14, _translate("Dialog", "230400"))
        self.label_2.setText(_translate("Dialog", "Baud Rate:"))
        self.label_3.setText(_translate("Dialog", "Send/Receive on Comm.Channel"))

        

        list = get_connected_com_ports()

        #print(list)

        self.comboBox_2.setItemText(0, _translate("Dialog", "choose COM port"))
        if(list != None):
            i = 0
            for x in list:
             #print(i)
             self.comboBox_2.setItemText(i, _translate("Dialog", list[i]))
             i +=1
        
        #self.comboBox_2.setItemText(1, _translate("Dialog", "1"))
        # self.comboBox_2.setItemText(2, _translate("Dialog", "2"))
        # self.comboBox_2.setItemText(3, _translate("Dialog", "--"))
        # self.comboBox_2.setItemText(4, _translate("Dialog", "--"))
        

        self.label_4.setText(_translate("Dialog", "Data Bits :"))
        self.comboBox_3.setItemText(0, _translate("Dialog", "8"))
        self.comboBox_3.setItemText(1, _translate("Dialog", "7"))
        self.comboBox_3.setItemText(2, _translate("Dialog", "6"))
        self.comboBox_3.setItemText(3, _translate("Dialog", "5"))
        self.label_5.setText(_translate("Dialog", "Parity :"))
        self.comboBox_4.setItemText(0, _translate("Dialog", "None"))
        self.comboBox_4.setItemText(1, _translate("Dialog", "Even"))
        self.comboBox_4.setItemText(2, _translate("Dialog", "Odd"))
        self.comboBox_4.setItemText(3, _translate("Dialog", "Mark"))
        self.comboBox_4.setItemText(4, _translate("Dialog", "Space"))
        self.label_6.setText(_translate("Dialog", "Stop bits :"))
        self.comboBox_5.setItemText(0, _translate("Dialog", "1"))
        self.comboBox_5.setItemText(1, _translate("Dialog", "1.5"))
        self.comboBox_5.setItemText(2, _translate("Dialog", "2"))

    # def closeDialog(self):
    #    print("in close")
    #    Dialog = QtWidgets.QDialog()
    #    Dialog.accept()
       
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
