# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'try.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QFont
from setting import Ui_Dialog
import serial
from time import sleep

class Ui_MainWindow(Ui_Dialog):
    
    i = Ui_Dialog()
    
    

    def openSetting(self):
        self.window = QtWidgets.QDialog()
        self.ui = Ui_Dialog()
        self.ui.setupUi(self.window)
        self.window.show()
        # self.ui.pushButton_0.clicked.connect(self.ui.on_ok_button_clicked()) 
        self.ui.pushButton_0.clicked.connect(lambda : [self.ui.on_ok_button_clicked(), self.window.close()]) 
        #print(self.i.cox)
       
        #self.ui.pushButton_0.clicked.connect(self.ui.on_ok_button_clicked)
        # self.ui.pushButton_0.clicked.connect(self.window.close())
        
        

    def new_file(self):
        print("Clicked on new file")
    
    def open_file(self):
        print("Clicked on open file")
    
    def save_file(self):
        print("Clicked on save")

    def saveAs(self):
        print("Clicked on save as")

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(673, 433)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(40, 120, 501, 21))
        self.frame_3.setStyleSheet("background-color: rgb(223, 217, 255);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_24 = QtWidgets.QLabel(self.frame_3)
        self.label_24.setGeometry(QtCore.QRect(-10, 0, 51, 20))
        self.label_24.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_13.setGeometry(QtCore.QRect(70, -10, 431, 41))
        self.lineEdit_13.setObjectName("lineEdit_13")

        self.label = QtWidgets.QLabel(MainWindow)
        self.label.setGeometry(QtCore.QRect(200, 20, 300, 50))  # Adjust the geometry as needed
        self.label.setObjectName("label")
        #self.label.setText("Message :"+)
        font = QFont()
        font.setPointSize(12)
        self.label.setFont(font)

        # self.line_edit = QtWidgets.QLineEdit(MainWindow)
        # self.line_edit.setGeometry(QtCore.QRect(200, 40, 250, 30))  # Adjust the geometry as needed
        # self.line_edit.setObjectName("line_edit")


        self.frame_6 = QtWidgets.QFrame(self.centralwidget)
        self.frame_6.setGeometry(QtCore.QRect(40, 250, 501, 21))
        self.frame_6.setStyleSheet("background-color: rgb(223, 217, 255);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_25 = QtWidgets.QLabel(self.frame_6)
        self.label_25.setGeometry(QtCore.QRect(-10, 0, 51, 20))
        self.label_25.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_14.setGeometry(QtCore.QRect(70, -10, 431, 41))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(550, 170, 75, 21))
        self.pushButton_2.setStyleSheet("background-color: rgb(120, 219, 255);\n"
"background-color: rgb(24, 124, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 60, 51, 31))
        self.label_5.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\";\n"
"")
        self.label_5.setObjectName("label_5")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(40, 90, 501, 21))
        self.frame_2.setStyleSheet("background-color: rgb(223, 217, 255);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_26 = QtWidgets.QLabel(self.frame_2)
        self.label_26.setGeometry(QtCore.QRect(-10, 0, 51, 20))
        self.label_26.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.lineEdit_1 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_1.setGeometry(QtCore.QRect(70, -11, 431, 41))
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(40, 220, 81, 31))
        self.label_7.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\";\n"
"")
        self.label_7.setObjectName("label_7")
        self.frame_7 = QtWidgets.QFrame(self.centralwidget)
        self.frame_7.setGeometry(QtCore.QRect(40, 280, 501, 21))
        self.frame_7.setStyleSheet("background-color: rgb(223, 217, 255);")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_27 = QtWidgets.QLabel(self.frame_7)
        self.label_27.setGeometry(QtCore.QRect(-10, 0, 51, 20))
        self.label_27.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_16.setGeometry(QtCore.QRect(70, -10, 431, 41))
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(550, 250, 75, 21))
        self.pushButton_3.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_3.setStyleSheet("background-color: rgb(120, 219, 255);\n"
"background-color: rgb(24, 124, 255);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(40, 140, 81, 31))
        self.label_6.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Arial\";\n"
"")
        self.label_6.setObjectName("label_6")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(40, 170, 501, 21))
        self.frame_4.setStyleSheet("background-color: rgb(223, 217, 255);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_28 = QtWidgets.QLabel(self.frame_4)
        self.label_28.setGeometry(QtCore.QRect(-10, 0, 51, 20))
        self.label_28.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_15.setGeometry(QtCore.QRect(70, -10, 431, 41))
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(550, 90, 75, 21))
        self.pushButton.setStyleSheet("background-color: rgb(120, 219, 255);\n"
"background-color: rgb(24, 124, 255);")
        self.pushButton.setObjectName("pushButton")
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(40, 200, 501, 21))
        self.frame_5.setStyleSheet("background-color: rgb(223, 217, 255);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_29 = QtWidgets.QLabel(self.frame_5)
        self.label_29.setGeometry(QtCore.QRect(-10, 0, 51, 20))
        self.label_29.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_17.setGeometry(QtCore.QRect(70, -10, 431, 41))
        self.lineEdit_17.setObjectName("lineEdit_17")

        self.buttonBox = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.buttonBox.setGeometry(QtCore.QRect(160, 340, 156, 23))
        #self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")

        #
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.openSetting())
        


        self.pushButton_4.setGeometry(QtCore.QRect(530, 340, 75, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 673, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        # self.menuSettings = QtWidgets.QMenu(self.menubar)
        # self.menuSettings.setObjectName("menuSettings")
        # MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew_File = QtWidgets.QAction(MainWindow)
        self.actionNew_File.setObjectName("actionNew_File")
        self.actionOpen_File = QtWidgets.QAction(MainWindow)
        self.actionOpen_File.setObjectName("actionOpen_File")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.menuFile.addAction(self.actionNew_File)
        self.menuFile.addAction(self.actionOpen_File)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menubar.addAction(self.menuFile.menuAction())
        #self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_24.setText(_translate("MainWindow", "RX"))
        self.label_25.setText(_translate("MainWindow", "TX"))
        self.pushButton_2.setText(_translate("MainWindow", "Send"))
        self.label_5.setText(_translate("MainWindow", "CAN"))
        self.label_26.setText(_translate("MainWindow", "TX"))
        self.label_7.setText(_translate("MainWindow", "RS - 485"))
        self.label_27.setText(_translate("MainWindow", "RX"))
        self.pushButton_3.setText(_translate("MainWindow", "Send"))
        self.label_6.setText(_translate("MainWindow", "RS - 232"))
        self.label_28.setText(_translate("MainWindow", "TX"))
        self.pushButton.setText(_translate("MainWindow", "Send"))
        self.label_29.setText(_translate("MainWindow", "RX"))
        self.pushButton_4.setText(_translate("MainWindow", "Settings"))
        
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        
        # self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.actionNew_File.setText(_translate("MainWindow", "New File"))
        self.actionOpen_File.setText(_translate("MainWindow", "Open File"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as"))

        #Actions for the menu bar
        self.actionNew_File.triggered.connect(self.new_file)
        self.actionOpen_File.triggered.connect(self.open_file)
        self.actionSave.triggered.connect(self.save_file)
        self.actionSave_as.triggered.connect(self.saveAs)
        #--

        #Action for buttons
        self.pushButton.clicked.connect(self.on_pushButton1_clicked)
        self.pushButton_2.clicked.connect(self.on_pushButton2_clicked)
        self.pushButton_3.clicked.connect(self.on_pushButton3_clicked)
        #--

        # try:
        #     ser = serial.Serial('COM12', 9600,timeout=1)
        # except:
        #     print("COM port not connected")
        #     #raise SystemExit("Program aborted") #Exit exxecution

        # try:
        #         rs = ser.readline().decode("utf-8")
        
        #         if(rs != None and rs[0] == "1"):
        #                 print("response:"+rs[1])
        #                 self.lineEdit_13.setText(rs[1])
        #                 #break
        #         if(rs != None and rs[0] == "2"):
        #                 self.lineEdit_17.setText(rs[1])
        #                 print("response:"+rs[1])
        #         #break
        #         if(rs != None and rs[0] == "3"):
        #                 self.lineEdit_16.setText(rs[1])
        #                 print("response:"+rs[1])
        #         #break
        # except IndexError:
        #         print("Not getting value")

    #Transmit and call responce function
    def read(self):
        try:
            ser = serial.Serial('COM3', 9600,timeout=1)
            try:
                rs = ser.readline().decode("utf-8")
        
                if(rs != None and rs[0] == "1"):
                        print("response:"+rs[1])
                        self.lineEdit_13.setText(rs[1])
                        #break
                if(rs != None and rs[0] == "2"):
                        self.lineEdit_17.setText(rs[1])
                        print("response:"+rs[1])
                #break
                if(rs != None and rs[0] == "3"):
                        self.lineEdit_16.setText(rs[1])
                        print("response:"+rs[1])
                #break
            except IndexError:
                s1 = "Not getting value"
                print("Not getting value")
                self.label.setText("Message :"+s1)
        except:
            s = "COM port not connected"
            print("COM port not connected")
            self.label.setText("Message :"+s)

            #raise SystemExit("Program aborted") #Exit exxecution

        

    def on_pushButton1_clicked(self):
        line_edit_value = self.lineEdit_1.text() 
        print("transmitting: 1"+line_edit_value)
        # self.waitForResponse()
        self.read()
    def on_pushButton2_clicked(self):
        line_edit_value = self.lineEdit_15.text() 
        print("transmitting: 2"+line_edit_value)
        #self.waitForResponse()
        self.read()
    def on_pushButton3_clicked(self):
        line_edit_value = self.lineEdit_14.text() 
        print("transmitting: 3"+line_edit_value)
        # self.waitForResponse()
        self.read()
    
    #Response for push button
#     def waitForResponse(self):
#         #print("in wait")
#         try:
#             ser = serial.Serial('COM3', 9600,timeout=1)
#             try:
#                 rs = ser.readline().decode("utf-8")
        
#                 if(rs != None and rs[0] == "1"):
#                         print("response:"+rs[1])
#                         self.lineEdit_13.setText(rs[1])
#                         #break
#                 if(rs != None and rs[0] == "2"):
#                         self.lineEdit_17.setText(rs[1])
#                         print("response:"+rs[1])
#                 #break
#                 if(rs != None and rs[0] == "3"):
#                         self.lineEdit_16.setText(rs[1])
#                         print("response:"+rs[1])
#                 #break
#             except IndexError:
#                 s1 = "Not getting value"
#                 print("Not getting value")
#                 self.label.setText("Message :"+s1)
#         except:
#             s = "COM port not connected"
#             print("COM port not connected")
#             self.label.setText("Message :"+s)




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    ui.read()
    sys.exit(app.exec_())
