# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import serial
from PyQt5.QtCore import QTimer
from datetime import datetime

class CircleWidget(QtWidgets.QWidget):
    
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setMinimumSize(50, 50)
    def paintEvent(self, event):
        painter = QtGui.QPainter(self)
        painter.setRenderHint(QtGui.QPainter.Antialiasing)  # For smoother circles
        # painter.setPen(QtGui.QPen(QtGui.QColor(255, 0, 0), 2))  # Red color and pen width

        diameter = min(self.width(), self.height())
        circle_rect = QtCore.QRect(0, 0, diameter - 1, diameter - 1)
        painter.setBrush(QtGui.QColor(255, 0, 0)) # Red bg color
        painter.drawEllipse(circle_rect)


class Ui_Dialog(object):

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(934, 369)
        Dialog.setStyleSheet("background-color: rgb(153, 193, 241);\n" "")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(40, 320, 91, 25))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(Dialog.close) #for closing after clicking on exit
        
        # self.pushButton_1 = QtWidgets.QPushButton(Dialog)
        # self.pushButton_1.setGeometry(QtCore.QRect(600,8,91,25))
        # self.pushButton_1.setObjectName("pushButton_1")
        
        
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(320, 10, 201, 17))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(21, 44, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(153, 193, 241))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(204, 224, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 96, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 129, 161))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(21, 44, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(21, 44, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(153, 193, 241))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(153, 193, 241))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(204, 224, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(21, 44, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(21, 44, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(153, 193, 241))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(204, 224, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 96, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 129, 161))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(21, 44, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(21, 44, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(153, 193, 241))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(153, 193, 241))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(204, 224, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(21, 44, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(21, 44, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(153, 193, 241))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(204, 224, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 96, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 129, 161))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(21, 44, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(21, 44, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(153, 193, 241))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(153, 193, 241))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(153, 193, 241))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(21, 44, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.label.setPalette(palette)
        self.label.setStyleSheet("color: rgb(21, 44, 240);")
        self.label.setObjectName("label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 30, 931, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.formFrame = QtWidgets.QFrame(Dialog)
        self.formFrame.setGeometry(QtCore.QRect(10, 90, 211, 161))
        self.formFrame.setStyleSheet("background-color: rgb(246, 245, 244);")
        self.formFrame.setObjectName("formFrame")
        self.formLayout = QtWidgets.QFormLayout(self.formFrame)
        self.formLayout.setObjectName("formLayout")
        self.label_5 = QtWidgets.QLabel(self.formFrame)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)

        #pickup voltage 1
        self.lineEdit = QtWidgets.QLineEdit(self.formFrame)
        self.lineEdit.setStyleSheet("background-color: rgb(153, 193, 241);")
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.label_6 = QtWidgets.QLabel(self.formFrame)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)

        #Drop voltage 1
        self.lineEdit_2 = QtWidgets.QLineEdit(self.formFrame)
        self.lineEdit_2.setStyleSheet("background-color: rgb(153, 193, 241);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.label_7 = QtWidgets.QLabel(self.formFrame)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_7)

        #Current 1
        self.lineEdit_6 = QtWidgets.QLineEdit(self.formFrame)
        self.lineEdit_6.setStyleSheet("background-color: rgb(153, 193, 241);")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_6)
        self.label_8 = QtWidgets.QLabel(self.formFrame)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_8)

        #Coil Resistance 1
        self.lineEdit_8 = QtWidgets.QLineEdit(self.formFrame)
        self.lineEdit_8.setStyleSheet("background-color: rgb(153, 193, 241);")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_8)
        self.label_9 = QtWidgets.QLabel(self.formFrame)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_9)

        #Pnumatic pressure 1
        self.lineEdit_7 = QtWidgets.QLineEdit(self.formFrame)
        self.lineEdit_7.setStyleSheet("background-color: rgb(153, 193, 241);")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_7)
        self.gridFrame_2 = QtWidgets.QFrame(Dialog)
        self.gridFrame_2.setGeometry(QtCore.QRect(260, 90, 211, 221))
        self.gridFrame_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.gridFrame_2.setObjectName("gridFrame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridFrame_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_25 = QtWidgets.QLabel(self.gridFrame_2)
        self.label_25.setObjectName("label_25")
        self.gridLayout_3.addWidget(self.label_25, 4, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.gridFrame_2)
        self.label_24.setObjectName("label_24")
        self.gridLayout_3.addWidget(self.label_24, 0, 0, 1, 1)

        #Current 2
        self.lineEdit_19 = QtWidgets.QLineEdit(self.gridFrame_2)
        self.lineEdit_19.setStyleSheet("background-color: rgb(153, 193, 241);")
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.gridLayout_3.addWidget(self.lineEdit_19, 3, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.gridFrame_2)
        self.label_23.setObjectName("label_23")
        self.gridLayout_3.addWidget(self.label_23, 1, 0, 1, 1)

        #Pickup voltage 2
        self.lineEdit_24 = QtWidgets.QLineEdit(self.gridFrame_2)
        self.lineEdit_24.setStyleSheet("background-color: rgb(153, 193, 241);")
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.gridLayout_3.addWidget(self.lineEdit_24, 0, 1, 1, 1)

        #No.of operations 2
        self.lineEdit_22 = QtWidgets.QLineEdit(self.gridFrame_2)
        self.lineEdit_22.setStyleSheet("background-color: rgb(153, 193, 241);")
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.gridLayout_3.addWidget(self.lineEdit_22, 5, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.gridFrame_2)
        self.label_27.setObjectName("label_27")
        self.gridLayout_3.addWidget(self.label_27, 3, 0, 1, 1)

        #Drop voltage 2
        self.lineEdit_18 = QtWidgets.QLineEdit(self.gridFrame_2)
        self.lineEdit_18.setStyleSheet("background-color: rgb(153, 193, 241);")
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.gridLayout_3.addWidget(self.lineEdit_18, 1, 1, 1, 1)

        #Coil temperature 2
        self.lineEdit_21 = QtWidgets.QLineEdit(self.gridFrame_2)
        self.lineEdit_21.setStyleSheet("background-color: rgb(153, 193, 241);")
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.gridLayout_3.addWidget(self.lineEdit_21, 6, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridFrame_2)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 5, 0, 1, 1)

        #Coil resistance 2
        self.lineEdit_20 = QtWidgets.QLineEdit(self.gridFrame_2)
        self.lineEdit_20.setStyleSheet("background-color: rgb(153, 193, 241);")
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.gridLayout_3.addWidget(self.lineEdit_20, 4, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.gridFrame_2)
        self.label_22.setObjectName("label_22")
        self.gridLayout_3.addWidget(self.label_22, 6, 0, 1, 1)
        self.gridFrame_3 = QtWidgets.QFrame(Dialog)
        self.gridFrame_3.setGeometry(QtCore.QRect(610, 90, 211, 221))
        self.gridFrame_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.gridFrame_3.setObjectName("gridFrame_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridFrame_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_29 = QtWidgets.QLabel(self.gridFrame_3)
        self.label_29.setObjectName("label_29")
        self.gridLayout_4.addWidget(self.label_29, 3, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridFrame_3)
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 4, 0, 1, 1)

        #Drop voltage 3
        self.lineEdit_26 = QtWidgets.QLineEdit(self.gridFrame_3)
        self.lineEdit_26.setStyleSheet("background-color: rgb(153, 193, 241);")
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.gridLayout_4.addWidget(self.lineEdit_26, 1, 1, 1, 1)

        #current 3
        self.lineEdit_23 = QtWidgets.QLineEdit(self.gridFrame_3)
        self.lineEdit_23.setStyleSheet("background-color: rgb(153, 193, 241);")
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.gridLayout_4.addWidget(self.lineEdit_23, 2, 1, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.gridFrame_3)
        self.label_31.setObjectName("label_31")
        self.gridLayout_4.addWidget(self.label_31, 2, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.gridFrame_3)
        self.label_30.setObjectName("label_30")
        self.gridLayout_4.addWidget(self.label_30, 0, 0, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.gridFrame_3)
        self.label_33.setObjectName("label_33")
        self.gridLayout_4.addWidget(self.label_33, 5, 0, 1, 1)

        #Coil temperature 3
        self.lineEdit_29 = QtWidgets.QLineEdit(self.gridFrame_3)
        self.lineEdit_29.setStyleSheet("background-color: rgb(153, 193, 241);")
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.gridLayout_4.addWidget(self.lineEdit_29, 5, 1, 1, 1)

        #Coil resistance 3
        self.lineEdit_27 = QtWidgets.QLineEdit(self.gridFrame_3)
        self.lineEdit_27.setStyleSheet("background-color: rgb(153, 193, 241);")
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.gridLayout_4.addWidget(self.lineEdit_27, 3, 1, 1, 1)

        #No.of operations 3
        self.lineEdit_28 = QtWidgets.QLineEdit(self.gridFrame_3)
        self.lineEdit_28.setStyleSheet("background-color: rgb(153, 193, 241);")
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.gridLayout_4.addWidget(self.lineEdit_28, 4, 1, 1, 1)

        #pickup voltage 3
        self.lineEdit_25 = QtWidgets.QLineEdit(self.gridFrame_3)
        self.lineEdit_25.setStyleSheet("background-color: rgb(153, 193, 241);")
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.gridLayout_4.addWidget(self.lineEdit_25, 0, 1, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.gridFrame_3)
        self.label_32.setObjectName("label_32")
        self.gridLayout_4.addWidget(self.label_32, 1, 0, 1, 1)
        self.formFrame_2 = QtWidgets.QFrame(Dialog)
        self.formFrame_2.setGeometry(QtCore.QRect(470, 90, 101, 221))
        self.formFrame_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.formFrame_2.setObjectName("formFrame_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formFrame_2)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_20 = QtWidgets.QLabel(self.formFrame_2)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_20)
        self.label_26 = QtWidgets.QLabel(self.formFrame_2)
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_26)
        # self.label_11 = QtWidgets.QLabel(self.formFrame_2)
        # self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        # self.label_11.setObjectName("label_11")

        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setText("Bad")
        self.label_11.setGeometry(515, 210, 30, 10)  
        self.label_11.setStyleSheet("background-color: white")

        self.label_35 = QtWidgets.QLabel(Dialog)
        self.label_35.setText("Indication")
        self.label_35.setGeometry(502, 230, 50, 10)  
        self.label_35.setStyleSheet("background-color: white")

        

        frame = QtWidgets.QFrame(Dialog)
        frame.setGeometry(819,209,102,102)  #820, 90, 101, 121
        frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        # frame.setStyleSheet("background-color: white;")
        frame.setStyleSheet("background-color: white; border: 1px solid white;")  # Set white background and border

        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setText("Bad")
        self.label_12.setGeometry(863, 210, 30, 10)  
        self.label_12.setStyleSheet("background-color: white")
        # self.label_12.setWindowOpacity(1)

        self.label_36 = QtWidgets.QLabel(Dialog)
        self.label_36.setParent(Dialog)
        self.label_36.setText("Indication")
        self.label_36.setGeometry(852, 230, 50, 10)  
        self.label_36.setStyleSheet("background-color: white")
        # self.label_12.setWindowOpacity(0)
        self.label_36.raise_()


        
        
        # self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.label_11)
        # self.label_35 = QtWidgets.QLabel(self.formFrame_2)
        # self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        # self.label_35.setObjectName("label_35")
        # self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.label_35)
        self.label_18 = QtWidgets.QLabel(self.formFrame_2)
        self.label_18.setText("")
        self.label_18.setPixmap(QtGui.QPixmap("../Downloads/Ellipse 1.png"))
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.label_18)
        self.label_10 = QtWidgets.QLabel(self.formFrame_2)
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("../Downloads/Ellipse 2.png"))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_10)
        self.formFrame_3 = QtWidgets.QFrame(Dialog)
        self.formFrame_3.setGeometry(QtCore.QRect(820, 90, 101, 121))
        self.formFrame_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.formFrame_3.setObjectName("formFrame_3")
        # self.formFrame_3.windowOpacity(0)
        self.formLayout_3 = QtWidgets.QFormLayout(self.formFrame_3)
        self.formLayout_3.setObjectName("formLayout_3")
        
        self.label_21 = QtWidgets.QLabel(self.formFrame_3)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_21)
        self.label_28 = QtWidgets.QLabel(self.formFrame_3)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_28)
        # self.label_12 = QtWidgets.QLabel(self.formFrame_3)
        # self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        # self.label_12.setObjectName("label_12")
        # self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.label_12)
        # self.label_36 = QtWidgets.QLabel(self.formFrame_3)
        # self.label_36.setAlignment(QtCore.Qt.AlignCenter)
        # self.label_36.setObjectName("label_36")
        # self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.label_36)
        self.label_19 = QtWidgets.QLabel(self.formFrame_3)
        self.label_19.setText("")
        self.label_19.setPixmap(QtGui.QPixmap("../Downloads/Ellipse 1.png"))
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.label_19)
        self.label_15 = QtWidgets.QLabel(self.formFrame_3)
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap("../Downloads/Ellipse 2.png"))
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_15)

        self.circle_widget = CircleWidget(Dialog)
        self.circle_widget.setGeometry(500, 150, 4, 4)  # Set the position and size of the circle widget
        #self.circle_widget.setStyleSheet("background-color: black;")
        

        self.circle_widget2 = CircleWidget(Dialog)
        self.circle_widget2.setGeometry(500, 250, 4, 4)
        self.circle_widget2.setStyleSheet("background-color: black;")

        self.circle_widget3 = CircleWidget(Dialog)
        self.circle_widget3.setGeometry(850, 150, 4, 4) #asdf

        self.circle_widget4 = CircleWidget(Dialog)
        self.circle_widget4.setGeometry(850, 250, 4, 4)

        #NEW FUNCTION CALLES
        self.qTimer = QTimer()
        self.qTimer.setInterval(45)
        self.qTimer.timeout.connect(self.putValues)
        self.qTimer.start()
        #NEW FUNCTION CALLES

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    
        

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "Exit"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline; color:#1a5fb4;\">Relay&amp;Contactor Test Bench</span></p></body></html>"))
        
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#1c71d8;\">Eletro Pnumatic Contactor</span></p></body></html>"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#1c71d8;\">Electro-Magnetic Contactor</span></p></body></html>"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#1c71d8;\">Electro-Magnetic Contactor</span></p></body></html>"))
        self.label_5.setText(_translate("Dialog", "Pickup Voltage:"))
        self.label_6.setText(_translate("Dialog", "Drop voltage:"))
        self.label_7.setText(_translate("Dialog", "Current:"))
        self.label_8.setText(_translate("Dialog", "Coil Resistance:"))
        self.label_9.setText(_translate("Dialog", "Pnumatic Pressure:"))
        self.label_25.setText(_translate("Dialog", "Coil Resistance:"))
        self.label_24.setText(_translate("Dialog", "Pickup Voltage:"))
        self.label_23.setText(_translate("Dialog", "Drop voltage:"))
        self.label_27.setText(_translate("Dialog", "Current:"))
        self.label_13.setText(_translate("Dialog", "No.Of Operations:"))
        self.label_22.setText(_translate("Dialog", "Coil Temperature:"))
        self.label_29.setText(_translate("Dialog", "Coil Resistance:"))
        self.label_14.setText(_translate("Dialog", "No.Of Operations:"))
        self.label_31.setText(_translate("Dialog", "Current:"))
        self.label_30.setText(_translate("Dialog", "Pickup Voltage:"))
        self.label_33.setText(_translate("Dialog", "Coil Temperature:"))
        self.label_32.setText(_translate("Dialog", "Drop voltage:"))
        self.label_20.setText(_translate("Dialog", "Healthy"))
        self.label_26.setText(_translate("Dialog", "Indication"))
        # self.label_11.setText(_translate("Dialog", "Bad"))
        # self.label_35.setText(_translate("Dialog", "Indication"))
        self.label_21.setText(_translate("Dialog", "Healthy"))
        self.label_28.setText(_translate("Dialog", "Indication"))
        # self.label_12.setText(_translate("Dialog", "Bad"))
        # self.label_36.setText(_translate("Dialog", "Indication"))
        
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(150, 320, 89, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.setText(_translate("Dialog", "Print"))
        self.pushButton_2.clicked.connect(self.on_pushButton_clicked)#for printing on click print button

        # self.pushButton_1.setText(_translate("Dialog", "Refresh"))
        # self.pushButton_1.clicked.connect(self.putValues)
 
    def putValues(self):
        try:
            self.ser = serial.Serial('/dev/ttyUSB0', 9600, timeout=1)
    
            try:
                
                rs = self.ser.readline().decode("utf-8")
                print("RX:",rs)

                if(rs.find("$")!=-1 and rs.find("#")!=-1):#rs[0] == '$' and rs[len(rs)-1] == '#'
                    if(rs != None and rs[3] == '1'):
                        seperatedData = rs.split(",")
                        self.lineEdit.setText(seperatedData[2])
                        self.lineEdit_2.setText(seperatedData[3])
                        self.lineEdit_6.setText(seperatedData[4])
                        self.lineEdit_8.setText(seperatedData[5])
                        self.lineEdit_7.setText(seperatedData[6])

                    if(rs != None and rs[3] == '2'):
                        seperatedData = rs.split(",")
                        self.lineEdit_24.setText(seperatedData[2])
                        self.lineEdit_18.setText(seperatedData[3])
                        self.lineEdit_19.setText(seperatedData[4])
                        self.lineEdit_20.setText(seperatedData[5])
                        self.lineEdit_22.setText(seperatedData[6])
                        self.lineEdit_21.setText(seperatedData[7])

                    if(rs != None and rs[3] == '3'):
                        seperatedData = rs.split(",")
                        self.lineEdit_25.setText(seperatedData[2])
                        self.lineEdit_26.setText(seperatedData[3])
                        self.lineEdit_23.setText(seperatedData[4])
                        self.lineEdit_27.setText(seperatedData[5])
                        self.lineEdit_28.setText(seperatedData[6])
                        self.lineEdit_29.setText(seperatedData[7])
                    

            except IndexError:
                # s1 = "Not getting value"
                print("Not getting value")
        except:
            print("COM port not connected")
        
    # def sendCommand(command):
    #     ser.write(command.encode('utf-8'))

    def printSerial(self,line):
        self.ser.write(line.encode('utf-8'))

    def on_pushButton_clicked(self):
        line_edit_value = self.lineEdit.text()
        line_edit_value1 = self.lineEdit_2.text()
        line_edit_value2 = self.lineEdit_6.text()
        line_edit_value3 = self.lineEdit_8.text()
        line_edit_value4 = self.lineEdit_7.text()
        
        # print("values of electro Pnumatic contactor")
        # print("------------------------------------")
        # print("Pickup voltage :"+line_edit_value)
        # print("Drop Voltage:"+line_edit_value1)
        # print("Current:"+line_edit_value2)
        # print("Coil resistance:"+line_edit_value3)
        # print("Pnumatic Pressure:"+line_edit_value4+"\n")
        
        DateTime = datetime.now()
        dt_string = DateTime.strftime("%d/%m/%Y %H:%M:%S")
        # print(dt_string)
        self.printSerial("     TACHYON AUTOMATIONS\n")
        self.printSerial("    Relay Test Jig Report\n")
        self.printSerial("Time Stamp : "+dt_string+"\n\n")
        self.printSerial("E P C\n")
        self.printSerial("--------\n")
        self.printSerial("Pickup voltage :"+line_edit_value+"\n")
        self.printSerial("Drop Voltage:"+line_edit_value1+"\n")
        self.printSerial("Current:"+line_edit_value2+"\n")
        self.printSerial("Coil resistance:"+line_edit_value3+"\n")
        self.printSerial("Pnumatic Pressure:"+line_edit_value4+"\n\n")
        
        
        line_edit_value11 = self.lineEdit_24.text()
        line_edit_value12 = self.lineEdit_18.text()
        line_edit_value13 = self.lineEdit_19.text()
        line_edit_value14 = self.lineEdit_20.text()
        line_edit_value15 = self.lineEdit_22.text()
        line_edit_value16 = self.lineEdit_21.text()
        
        # print("values of electro Magnetic contactor")
        # print("------------------------------------")
        # print("Pickup voltage :"+line_edit_value11)
        # print("Drop Voltage:"+line_edit_value12)
        # print("Current:"+line_edit_value13)
        # print("Coil resistance:"+line_edit_value14)
        # print("No.of Operations:"+line_edit_value15)
        # print("Coil temperature:"+line_edit_value16+"\n")

        self.printSerial("E M C\n")
        self.printSerial("--------\n")
        self.printSerial("Pickup voltage :"+line_edit_value11+"\n")
        self.printSerial("Drop Voltage:"+line_edit_value12+"\n")
        self.printSerial("Current:"+line_edit_value13+"\n")
        self.printSerial("Coil resistance:"+line_edit_value14+"\n")
        self.printSerial("No.of Operations:"+line_edit_value15+"\n")
        self.printSerial("Coil temperature:"+line_edit_value16+"\n\n")
        
        line_edit_value21 = self.lineEdit_25.text()
        line_edit_value22 = self.lineEdit_26.text()
        line_edit_value23 = self.lineEdit_23.text()
        line_edit_value24 = self.lineEdit_27.text()
        line_edit_value25 = self.lineEdit_28.text()
        line_edit_value26 = self.lineEdit_29.text()
        
        # print("values of electro Magnetic contactor")
        # print("------------------------------------")
        # print("Pickup voltage :"+line_edit_value21)
        # print("Drop Voltage:"+line_edit_value22)
        # print("Current:"+line_edit_value23)
        # print("Coil resistance:"+line_edit_value24)
        # print("No.of Operations:"+line_edit_value25)
        # print("Coil temperature:"+line_edit_value26)

        self.printSerial("E M C \n")
        self.printSerial("--------\n")
        self.printSerial("Pickup voltage :"+line_edit_value21+"\n")
        self.printSerial("Drop Voltage:"+line_edit_value22+"\n")
        self.printSerial("Current:"+line_edit_value23+"\n") 
        self.printSerial("Coil resistance:"+line_edit_value24+"\n")
        self.printSerial("No.of Operations:"+line_edit_value25+"\n")
        self.printSerial("Coil temperature:"+line_edit_value26+"\n\n\n\n\n")
        

    # Perform additional actions here

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    ui.putValues()
    sys.exit(app.exec_())
